controller_manager_ns: ''
controller_list:
  - name: /cal/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: /cal/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  # - name: /cal/both_arms_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - LShoulderPitch
  #     - LShoulderRoll
  #     - LElbowYaw
  #     - LElbowRoll
  #     - LWristYaw
  #     - RShoulderPitch
  #     - RShoulderRoll
  #     - RElbowYaw
  #     - RElbowRoll
  #     - RWristYaw
  # - name: /cal/left_arm_wholebody_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - KneePitch
  #     - HipPitch
  #     - HipRoll
  #     - LShoulderPitch
  #     - LShoulderRoll
  #     - LElbowYaw
  #     - LElbowRoll
  #     - LWristYaw
  # - name: /cal/right_arm_wholebody_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - KneePitch
  #     - HipPitch
  #     - HipRoll
  #     - RShoulderPitch
  #     - RShoulderRoll
  #     - RElbowYaw
  #     - RElbowRoll
  #     - RWristYaw
  - name: /cal/pelvis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - KneePitch
      - HipPitch
      - HipRoll
  - name: /cal/head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - HeadYaw
      - HeadPitch
  # - name: /cal/left_hand_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - LHand
  # - name: /cal/right_hand_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - RHand
