JulietteY20MP:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - KneePitch
      - HipPitch
      - HipRoll
      - HeadYaw
      - HeadPitch
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - LHand
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
      - RHand
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: right_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - RShoulderPitch
        - RShoulderRoll
        - RElbowYaw
        - RElbowRoll
        - RWristYaw
    - name: left_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - LShoulderPitch
        - LShoulderRoll
        - LElbowYaw
        - LElbowRoll
        - LWristYaw
    - name: both_arms_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - LShoulderPitch
        - LShoulderRoll
        - LElbowYaw
        - LElbowRoll
        - LWristYaw
        - RShoulderPitch
        - RShoulderRoll
        - RElbowYaw
        - RElbowRoll
        - RWristYaw
    - name: right_arm_wholebody_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - KneePitch
        - HipPitch
        - HipRoll
        - RShoulderPitch
        - RShoulderRoll
        - RElbowYaw
        - RElbowRoll
        - RWristYaw
    - name: left_arm_wholebody_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - KneePitch
        - HipPitch
        - HipRoll
        - LShoulderPitch
        - LShoulderRoll
        - LElbowYaw
        - LElbowRoll
        - LWristYaw
    - name: both_arms_wholebody_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - KneePitch
        - HipPitch
        - HipRoll
        - LShoulderPitch
        - LShoulderRoll
        - LElbowYaw
        - LElbowRoll
        - LWristYaw
        - RShoulderPitch
        - RShoulderRoll
        - RElbowYaw
        - RElbowRoll
        - RWristYaw
    - name: right_hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        []
    - name: left_hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        []
    - name: base_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        []
    - name: head_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - HeadYaw
        - HeadPitch